"use client";

import { NextPage } from "next";
import { useEffect } from "react";
import { usePageTitleStore } from "@/app/store/pageTitle.store";
import { DataTable, ColumnDef } from "@/app/components/DataTable";

// Type for Report data
type Report = {
  _id: string;
  name: string;
  type: "Financial" | "Operational" | "Compliance";
  generatedBy: string;
  date: string;
};

// Dummy data for reports
const dummyReports: Report[] = [
  { _id: "60d0fe4f5311236168a11001", name: "Q3 Financial Summary", type: "Financial", generatedBy: "Admin User", date: "2023-10-01" },
  { _id: "60d0fe4f5311236168a11002", name: "October On-Time Performance", type: "Operational", generatedBy: "System", date: "2023-11-01" },
  { _id: "60d0fe4f5311236168a11003", name: "GDPR Compliance Audit", type: "Compliance", generatedBy: "Admin User", date: "2023-09-15" },
];

// Column definitions for the report table
const columns: ColumnDef<Report>[] = [
  { header: "Report Name", accessorKey: "name" },
  { header: "Type", accessorKey: "type" },
  { header: "Generated By", accessorKey: "generatedBy" },
  { header: "Date", accessorKey: "date" },
  {
      header: "Actions",
      accessorKey: "_id",
      cell: () => (
          <div className="flex gap-2">
              <button className="text-xs bg-blue-500 text-white px-2 py-1 rounded hover:bg-blue-600">View</button>
              <button className="text-xs bg-green-500 text-white px-2 py-1 rounded hover:bg-green-600">Download</button>
          </div>
      )
  }
];

const OperationalReportsPage: NextPage = () => {
    const { setTitle } = usePageTitleStore();

    useEffect(() => {
        setTitle("Operational Reports");
    }, [setTitle]);

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="mb-8">
        <div className="bg-white p-6 rounded-lg shadow-md">
            <h2 className="text-xl font-bold mb-4">Generate New Report</h2>
            <button className="bg-purple-600 text-white px-4 py-2 rounded-lg hover:bg-purple-700">Generate Report</button>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-bold mb-4 text-gray-800">Generated Reports</h2>
        <DataTable data={dummyReports} columns={columns} filterColumn="type" />
      </div>
    </div>
  );
};

export default OperationalReportsPage;
