"use client";

import { NextPage } from "next";
import { useEffect, useState } from "react";
import { usePageTitleStore } from "@/app/store/pageTitle.store";
import { DataTable, ColumnDef } from "@/app/components/DataTable";
import { Button } from "@/app/components/ui/Button";
import Pagination from "@/app/components/Pagination";

// Type for Report data
type Report = {
  _id: string;
  name: string;
  type: "Financial" | "Operational" | "Compliance";
  generatedBy: string;
  date: string;
};

// Dummy data for reports
const dummyReports: Report[] = [
  { _id: "60d0fe4f5311236168a11001", name: "Q3 Financial Summary", type: "Financial", generatedBy: "Admin User", date: "2023-10-01" },
  { _id: "60d0fe4f5311236168a11002", name: "October On-Time Performance", type: "Operational", generatedBy: "System", date: "2023-11-01" },
  { _id: "60d0fe4f5311236168a11003", name: "GDPR Compliance Audit", type: "Compliance", generatedBy: "Admin User", date: "2023-09-15" },
];

// Column definitions for the report table
const columns: ColumnDef<Report>[] = [
  { header: "Report Name", accessorKey: "name" },
  { header: "Type", accessorKey: "type" },
  { header: "Generated By", accessorKey: "generatedBy" },
  { header: "Date", accessorKey: "date" },
  {
      header: "Actions",
      accessorKey: "_id",
      cell: () => (
          <div className="flex gap-2">
              <Button size="sm">View</Button>
              <Button size="sm" variant="success">Download</Button>
          </div>
      )
  }
];

const OperationalReportsPage: NextPage = () => {
    const { setTitle } = usePageTitleStore();
    const [currentPage, setCurrentPage] = useState(1);
    const [itemsPerPage, setItemsPerPage] = useState(10);

    useEffect(() => {
        setTitle("Operational Reports");
    }, [setTitle]);

    const totalPages = Math.ceil(dummyReports.length / itemsPerPage);

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="mb-8">
        <div className="bg-white p-6 rounded-lg shadow-md">
            <h2 className="text-xl font-bold mb-4">Generate New Report</h2>
            <Button>Generate Report</Button>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-bold mb-4 text-gray-800">Generated Reports</h2>
        <DataTable
            data={dummyReports}
            columns={columns}
            filterColumn="type"
            currentPage={currentPage}
            itemsPerPage={itemsPerPage}
            onPageChange={setCurrentPage}
            onItemsPerPageChange={setItemsPerPage}
        />
        <Pagination
            currentPage={currentPage}
            totalPages={totalPages}
            onPageChange={setCurrentPage}
            itemsPerPage={itemsPerPage}
            onItemsPerPageChange={setItemsPerPage}
        />
      </div>
    </div>
  );
};

export default OperationalReportsPage;
